config/routes.rb
Rails.application.routes.draw do
  resources :casts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cast.rb
class Cast < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: %i[ show edit update destroy ]

  # GET /casts or /casts.json
  def index
    @casts = Cast.all
  end

  # GET /casts/1 or /casts/1.json
  def show
  end

  # GET /casts/new
  def new
    @cast = Cast.new
  end

  # GET /casts/1/edit
  def edit
  end

  # POST /casts or /casts.json
  def create
    @cast = Cast.new(cast_params)

    respond_to do |format|
      if @cast.save
        format.html { redirect_to @cast, notice: "Cast was successfully created." }
        format.json { render :show, status: :created, location: @cast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casts/1 or /casts/1.json
  def update
    respond_to do |format|
      if @cast.update(cast_params)
        format.html { redirect_to @cast, notice: "Cast was successfully updated." }
        format.json { render :show, status: :ok, location: @cast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casts/1 or /casts/1.json
  def destroy
    @cast.destroy
    respond_to do |format|
      format.html { redirect_to casts_url, notice: "Cast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cast
      @cast = Cast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cast_params
      params.require(:cast).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/views/casts/_form.html.erb
<%= form_with(model: cast) do |form| %>
  <% if cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
        <% cast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casts/edit.html.erb
<h1>Editing Cast</h1>

<%= render 'form', cast: @cast %>

<%= link_to 'Show', @cast %> |
<%= link_to 'Back', casts_path %>

app/views/casts/index.html.erb
<div id="terminal" style="width:800px;height:600px"></div>

app/views/casts/new.html.erb
<h1>New Cast</h1>

<%= render 'form', cast: @cast %>

<%= link_to 'Back', casts_path %>

app/views/casts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cast.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @cast.url %>
</p>

<%= link_to 'Edit', edit_cast_path(@cast) %> |
<%= link_to 'Back', casts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>